### PR TITLE
Fix a bug when doing reset in the sample app

### PR DESCRIPTION
**Pull request by Mygod**
Steps to reproduce:

1. Press "Subscreen";
2. Press "Reset";
3. Press back button in the top left twice;
4. Havoc!

### CODE REVIEW

**Comment by Mygod** [comment]
By the way, I suggest uploading a sample app in the releases so that it saves everybody's time.

**Review by consp1racy — CHANGES_REQUESTED** [review]
Thanks for the PR, this is a good catch! Although I'd like you to do some polishing first:

    getSupportFragmentManager().popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);

1) This will pop everything from the stack in one go. You don't have to touch a `while` loop.
2) Since the next command is an asynchronous fragment transaction perhaps it would be better for this operation to be async as well. I'm not a fragment manager expert but there's definitely more room for internal optimizations if we let both operations run async.

**Comment by consp1racy** [comment]
> By the way, I suggest uploading a sample app in the releases so that it saves everybody's time.

What do you mean? Publishing the sample app in Play Store? I guess that's doable.

**Comment by Mygod** [comment]
Fixed!

Oh I mean you can publish apks here: https://github.com/consp1racy/android-support-preference/releases
If you want to do it on Google Play, that's also nice. :+1:

**Comment by consp1racy** [comment]
That's cool! Although I've never worked with github releases before and have no ides where to start. Do you have some tutorials on hand?

**Comment by Mygod** [comment]
How's this: https://help.github.com/articles/creating-releases/

**Pull request merged**
